#!/bin/sh
sed -i "s_Configure::write('Auth.allowAll', true);_Configure::write('Auth.allowAll', false);_g" /var/www/ombi60.biz/current/app/config/bootstrap.local.php
sed -i "s_Configure::write('Auth.allowAll', true);_Configure::write('Auth.allowAll', false);_g" /var/www/ombi60.com/current/app/config/bootstrap.local.php
