#!/bin/sh
sed -i "s_Configure::write('debug', 0);_Configure::write('debug', 2);_g" /var/www/ombi60.biz/current/app/config/bootstrap.local.php
sed -i "s_Configure::write('debug', 0);_Configure::write('debug', 2);_g" /var/www/ombi60.com/current/app/config/bootstrap.local.php
